### ISSUE TITLE
Sundry tweaks for front-page-us-election-headpiece

### ISSUE THREAD

**Issue by aendrew** [Financial-Times/next-front-page#1171]
# Via @kavanagh:
- [x] Jarring transition switching panels, could there be a pause of blank, and or a fade in.
- [x] Alaska seems clipped at the bottom
- [x] Large Clinton/Trump labels on mobile
- [x] Map seems smaller than the original design
- [x] White dividing lines shouldn't be white, see Brexit screengrab below:
  <img width="870" alt="screen shot 2016-06-24 at 05 08 54" src="https://cloud.githubusercontent.com/assets/185041/19595612/a0de3580-9782-11e6-94d8-1b5a4e63e9e9.png">
- [x] In this screen grab you can again see the spacing issues with yellow highlights to the left and right of stories. Also the space above the main headline seems to large. Can we do something nice about the blue space/highlight. Pink highlight: tabs divider lines are too big.
  <img width="983" alt="financial_times 3" src="https://cloud.githubusercontent.com/assets/185041/19595708/15b800f2-9783-11e6-87d0-c6a8f549ea2b.png">
- [x] For the Brexit version, on mobile, we left-align the tab labels
- [x] Missing divider lines

  <img width="497" alt="financial_times 1" src="https://cloud.githubusercontent.com/assets/185041/19595722/3010ea90-9783-11e6-95ee-caef89fcca35.png">
- [x] The green highlight shows how the diver lines are too tall. The yellow highlight show extra space to the left and right of stories. The pink highlight show the arrow is a little bit squiffy. It should be an equilateral and have about 1px away from the bar… a bit of space between.
  <img width="758" alt="financial_times 2" src="https://cloud.githubusercontent.com/assets/185041/19595697/035caa66-9783-11e6-8d72-9f9da6217969.png">
- [x] Headline on mobile seems too small and the space above seems to big. Also note the stand first needs to be grey. And perhaps more difference in font size from the headline.
  <img width="407" alt="financial_times 4" src="https://cloud.githubusercontent.com/assets/185041/19595732/3d3d5b90-9783-11e6-897b-4137a57b62d3.png">
- [x] Size (too small on desktop) and colour of standfirst (should be grey) on the main story, see Brexit screen grab
  <img width="1201" alt="screen shot 2016-06-23 at 22 43 20" src="https://cloud.githubusercontent.com/assets/185041/19595630/b3c38aba-9782-11e6-97ed-cb79b95777bd.png">
- [x] When an SVG isn’t loaded we get the thing shown in the screenshot (“Interactive Not Found”) which is the interactive server’s 404 page. If this does happen in production errors should result in either a) blank tab or b) hiding the markets tab. But defo not showing this.
  <img width="587" alt="financial_times" src="https://cloud.githubusercontent.com/assets/185041/19595684/f1abbde8-9782-11e6-82df-fe9164b7bd8e.png">
- [x] When changing from the President to the Senate the  bars jump - space above the bars is not the same
- [x] also vertical alignment of the Clinton/Trump labels
- [x] I’m getting errors loading a resource, I’m not sure if this is our components, my browser told me it was coming from a script called Progress indicator: This was an example resource: 
  > * Progress indicator: http://s1.ft-static.com/m/font/e9d47971-b7d8-4663-8c9b-3a0b425e981f-3.woff
  <img width="572" alt="https___www_ft_com__is_not_available_and_slack" src="https://cloud.githubusercontent.com/assets/185041/19595645/c8b3cbb0-9782-11e6-8ca1-13109401a172.png">
    - I haven't encountered this, am guessing it was an issue that was resolved upstream.
- [x] MyFT button doesn't work
    - Investigation leads me to believe it's something needing to be setup in Methode — clicking the button yields the following 500:
      <img width="871" alt="screen shot 2016-10-25 at 15 08 33" src="https://cloud.githubusercontent.com/assets/185041/19689374/13858242-9ac5-11e6-9aca-d65c07ecf4a7.png">
    - Deferred to #1183.
- [x] Is the hit target of the tabs big enough, especially small screens.
- [x] Overlapping text / Black diagonal lines / Clinton/Trump labels too big and not v aligned.
<img width="419" alt="financial_times 5" src="https://cloud.githubusercontent.com/assets/185041/19595746/4e3f149c-9783-11e6-9eaa-7def59a09115.png">

# Via Steve:

## Universal
- [x] diagonal hatch marks need to be #333333
- [x] hatches need to be closer together, this does the trick  background-size: 7px; (ideally SVG remade at 7px instead of 10px)
- [x] divider lines rgba(255, 255, 255, 0.38)
- [x] divider lines have disappeared from above each story in four story block
- [x] columnist blue #80cdff
- [x] background colour for columnist headshot #4d5253
- [x] border for columnist headshot 1px solid rgba(255, 255, 255, 0.38);
- [x] main headline margin-top -6px
- [x] standfirst margin-top 6px
- [x] standfirst color #cccccc
- [x] senate legend boxes 20px W x 10px H
- [x] senate legend margin-top: 5px
- [x] Full results map link regular not italic, seems to be Bentons Sans for some reason
- [x] minibar tab dividers same height as labels
- [x] Triangle marker needs to be equivalent of 10px W x 7px H
- [x] Minibar labels/legend text color: #cccccc
- [x] Minibar footnote text color: #999999

## Mobile (S)
- [x] main headline 32px/34px
- [x] bar labels mobile 22px/29px
- [x] tabs need to be left-aligned
- [x] remove left padding on stories so they line up with bars/photo

## Tablet (M)
- [x] remove left padding on stories so they line up with bars/photo
- [x] main headline 50px/52px
- [x] standfirst 18px
- [x] main image margin-top 14px

## Desktop (L)
- [x] main image margin-top 14px
- [x] main headline 50px/52px
- [x] standfirst 18px
- [x] standfirst margin-bottom: 10px
- [x] map size 92px x 61px

## Desktop (XL)
- [x] standfirst margin-bottom: 10px
- [x] map size 92px x 61px

# Via @callumlocke 
- [x] #1168 Timestamps wrong colour

**Comment by callumlocke** [comment]
nice work putting this together!

**Comment by aendrew** [comment]
Removing `blocker` label because I'm not sure if that'll interfere with anything in the parent project. Please push changes to [`us-election-headpiece-tweaks`][1] branch.

[1]: https://github.com/Financial-Times/next-front-page/tree/us-election-headpiece-tweaks
